DROP TABLE IF EXISTS TLD_ALLOC_ONBRD_PARM;

CREATE TABLE TLD_ALLOC_ONBRD_PARM 
( 
TLD_ALLOC_ONBRD_PARM_ID INT NOT NULL, 
TLD_ALLOC_PARM_TYP_CD INT NOT NULL,  
PARM_MVNDR_PRTY_ID INT,
PARM_ITEM_ID INT,
PARM_LOC_ID INT, 
PARM_LOC_TYP_CD VARCHAR(255),
PARM_FLG_VAL VARCHAR(255),
PARM_INTG_VAL INT, 
PARM_DT_VAL DATE,
PARM_CHAR_VAL VARCHAR(255),
PARM_DEC_VAL DECIMAL(10,2),
ACTV_FLG VARCHAR(255));

INSERT INTO TLD_ALLOC_ONBRD_PARM (TLD_ALLOC_ONBRD_PARM_ID, TLD_ALLOC_PARM_TYP_CD, PARM_MVNDR_PRTY_ID,
PARM_ITEM_ID, PARM_LOC_ID, PARM_LOC_TYP_CD,PARM_FLG_VAL,PARM_INTG_VAL,PARM_DT_VAL,PARM_CHAR_VAL,
PARM_DEC_VAL,ACTV_FLG)
VALUES (1299,2,null,4112743,2050,'SDC',null,10,null,null,null,'Y');

INSERT INTO TLD_ALLOC_ONBRD_PARM (TLD_ALLOC_ONBRD_PARM_ID, TLD_ALLOC_PARM_TYP_CD, PARM_MVNDR_PRTY_ID,
PARM_ITEM_ID, PARM_LOC_ID, PARM_LOC_TYP_CD,PARM_FLG_VAL,PARM_INTG_VAL,PARM_DT_VAL,PARM_CHAR_VAL,
PARM_DEC_VAL,ACTV_FLG)
VALUES (502,2,null,2617483,2448,'SDR',null,340,null,null,null,'Y');

INSERT INTO TLD_ALLOC_ONBRD_PARM (TLD_ALLOC_ONBRD_PARM_ID, TLD_ALLOC_PARM_TYP_CD, PARM_MVNDR_PRTY_ID,
PARM_ITEM_ID, PARM_LOC_ID, PARM_LOC_TYP_CD,PARM_FLG_VAL,PARM_INTG_VAL,PARM_DT_VAL,PARM_CHAR_VAL,
PARM_DEC_VAL,ACTV_FLG)
VALUES (331,2,null,2261437,2882,'TLD',null,100,null,null,null,'Y');


