DROP TABLE IF EXISTS AL_HEADER;
DROP SEQUENCE IF EXISTS ALLOCATION_HEADER_SEQ;

CREATE SEQUENCE ALLOCATION_HEADER_SEQ
 	START WITH     1
 	INCREMENT BY   1
 	NOCACHE
 	NOCYCLE;
 	
CREATE TABLE AL_HEADER (
 	ALLOCATION_ID NUMBER NOT NULL PRIMARY KEY,
 	ALLOCATION_TYPE_ID INT,
 	ALLOCATION_DATE DATE,
 	LAST_EDIT_DATE DATE,
 	SHIP_ON_DATE DATE,
 	ETA_DATE DATE,
 	DISTRIBUTION_DATE DATE,
 	STATUS_ID INT,
 	VENDOR_NUMBER VARCHAR(255),
 	PO_NUMBER INT,
 	DC_LOCATION_ID VARCHAR(255),
 	STORE_REQUESTED INT, 
 	STORE_REQUESTED_DUE_DATE DATE,
 	LOCATION_TYPE CHAR(1) NOT NULL CHECK(LOCATION_TYPE IN('S', 'D')),
 	LOCATION_ID VARCHAR(255),
 	CONSTRAINT PK_ALLOCATION_ID PRIMARY KEY(ALLOCATION_ID)
);