DROP TABLE IF EXISTS AL_PRODUCT;
DROP SEQUENCE IF EXISTS ALLOCATION_PRODUCT_SEQ;

CREATE SEQUENCE ALLOCATION_PRODUCT_SEQ
 	START WITH     1
 	INCREMENT BY   1
 	NOCACHE
 	NOCYCLE;
 	
CREATE TABLE AL_PRODUCT(
	ALLOCATION_ID NUMBER NOT NULL,
	PRODUCT_NUMBER INT,
	ORDER_QTY DECIMAL(10, 6),
	RECEIPT_QTY DECIMAL(10, 6),
	ORDER_QTY_PCT DECIMAL(10, 6),
	VENDOR_NUMBER VARCHAR(255),
	STATUS_ID INT,
	PO_PACK_SIZE DECIMAL(10, 6),
	DC_TRANSFER_PCT DECIMAL(10, 6),
	USE_MIN_MAX_POLICY INT,
	ROUND_PACK_SIZE INT, 
	BATCH_STATUS INT,
	BATCH_SUMBIT_DATE DATE,
	BATCH_COMPLETE_DATE DATE,
	QUANTITY_ADJUSTED INT,
	DISTRIBUTION_DATE TIMESTAMP,
	CONSTRAINT PK_ALLOCATION_ID PRIMARY KEY(ALLOCATION_ID)
);