DROP TABLE IF EXISTS AL_DETAIL;
DROP SEQUENCE IF EXISTS ALLOCATION_DETAIL_SEQ;

CREATE SEQUENCE ALLOCATION_DETAIL_SEQ
 	START WITH     1
 	INCREMENT BY   1
 	NOCACHE
 	NOCYCLE;
 
     
CREATE TABLE AL_DETAIL 
( 
ID NUMBER NOT NULL, 
ALLOCATION_ID NUMBER NOT NULL,
PRODUCT_NUMBER INT, 
LOCATION_TYPE CHAR(1) NOT NULL  CHECK(LOCATION_TYPE IN ('S','D')),
LOCATION_ID VARCHAR(255), 
DC_NUMBER VARCHAR(255), 
ETA_DATE DATE,
PACK_SIZE DECIMAL(10,2),
ALLOCATED_QUANTITY DECIMAL(10,2), 
ADJUSTED_QUANTITY DECIMAL(10,2),
CONSTRAINT PK_AL_DETAIL PRIMARY KEY(ID)
);


