DROP TABLE IF EXISTS AL_HEADER;
DROP SEQUENCE IF EXISTS ALLOCATION_HEADER_SEQ;
DROP TABLE IF EXISTS AL_DETAIL;
DROP SEQUENCE IF EXISTS ALLOCATION_DETAIL_SEQ;
DROP TABLE IF EXISTS AL_PRODUCT;
DROP SEQUENCE IF EXISTS ALLOCATION_PRODUCT_SEQ;

 
CREATE SEQUENCE ALLOCATION_HEADER_SEQ
 	START WITH     10025
 	INCREMENT BY   1
 	NOCACHE
 	NOCYCLE;
 	
CREATE SEQUENCE ALLOCATION_DETAIL_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE ALLOCATION_PRODUCT_SEQ
 	START WITH     1
 	INCREMENT BY   1
 	NOCACHE
 	NOCYCLE;
 	
CREATE TABLE AL_HEADER (
 	ALLOCATION_ID NUMBER NOT NULL,
 	ALLOCATION_TYPE_ID INT,
 	ALLOCATION_DATE DATE,
 	LAST_EDIT_DATE DATE,
 	SHIP_ON_DATE DATE,
 	ETA_DATE DATE,
  	STATUS_ID INT,
 	VENDOR_NUMBER VARCHAR(255),
 	PO_NUMBER INT,
 	CLASS1_ID INT,
 	LOCATION_TYPE CHAR(1) NOT NULL CHECK(LOCATION_TYPE IN('S', 'D')),
 	LOCATION_ID VARCHAR(255),
 	CONSTRAINT PK_ALLOCATION_ID PRIMARY KEY(ALLOCATION_ID)
);

     
CREATE TABLE AL_DETAIL 
( 
ID NUMBER NOT NULL, 
ALLOCATION_ID NUMBER NOT NULL,
PRODUCT_NUMBER INT, 
LOCATION_TYPE CHAR(1) NOT NULL  CHECK(LOCATION_TYPE IN ('S','D')),
LOCATION_ID VARCHAR(255), 
DC_NUMBER VARCHAR(255), 
ETA_DATE DATE,
PACK_SIZE DECIMAL(10,2),
ALLOCATED_QUANTITY DECIMAL(10,2), 
ADJUSTED_QUANTITY DECIMAL(10,2),
CONSTRAINT PK_AL_DETAIL PRIMARY KEY(ID),
CONSTRAINT FK_AL_DETAIL
     FOREIGN KEY (ALLOCATION_ID)
     REFERENCES AL_HEADER (ALLOCATION_ID)
);


 	
CREATE TABLE AL_PRODUCT(
	ID NUMBER NOT NULL, 
	ALLOCATION_ID NUMBER NOT NULL,
	PRODUCT_NUMBER INT,
	ORDER_QTY DECIMAL(10, 6),
	RECEIPT_QTY DECIMAL(10, 6),
	VENDOR_NUMBER VARCHAR(255),
	STATUS_ID INT,
	PO_PACK_SIZE DECIMAL(10, 6),
	QUANTITY_SOURCE INT,
	METHOD_ID INT,
	INCLUDE_EFF_INV INT,
	INCLUDE_PROMO_SALES INT,
	ALLOCATE_ALL INT,
	DC_TRANSFER_PCT DECIMAL(10, 6),
	USE_MIN_MAX_POLICY INT,
	MIN_SHELF DECIMAL(10, 6),
	MAX_SHELF DECIMAL(10, 6),
	DC_USE_MIN_MAX_POLICY INT,
	ROUND_PACK_SIZE INT, 
	ROUND_FIRST_PACK INT,
	METHOD_CLASS_LEVEL_ID INT,
	METHOD_TIME_FRAME INT,
	METHOD_WEEKS INT,
	METHOD_DAYS INT,
	METHOD_START_DATE DATE,
	PRE_DISTRIBUTED INT,
	PO_INNER_PACK_SIZE DECIMAL(10, 6),
	SHIP_LEVEL_IND INT,
	METHOD_EFF_INV_IND INT,
	CONSTRAINT PK_AL_PRODUCT PRIMARY KEY(ID),
	CONSTRAINT FK_AL_PRODUCT
     FOREIGN KEY (ALLOCATION_ID)
     REFERENCES AL_HEADER (ALLOCATION_ID)
);