DROP TABLE IF EXISTS TLALLOC_OVERAGE_STG;

CREATE TABLE TLALLOC_OVERAGE_STG 
( 
SEQUENCENUMBER NUMBER PRIMARY KEY, 
UPLOADID INT, 
LOCATIONID VARCHAR(255), 
PRODUCTCODE VARCHAR(255), 
OVERAGE_DAYS DECIMAL(10,3),
ACTIVEFLAG VARCHAR(255)
);



INSERT INTO TLALLOC_OVERAGE_STG (SEQUENCENUMBER, UPLOADID, LOCATIONID, PRODUCTCODE, OVERAGE_DAYS, ACTIVEFLAG)
VALUES (55,1513,'5096','103256',100,'Y');

INSERT INTO TLALLOC_OVERAGE_STG (SEQUENCENUMBER, UPLOADID, LOCATIONID, PRODUCTCODE, OVERAGE_DAYS, ACTIVEFLAG)
VALUES (56,1513,'5096','103256',100,'N');


