DROP TABLE IF EXISTS STG_TLD_ALLOC;

CREATE TABLE STG_TLD_ALLOC (
	TLD_DC_NBR VARCHAR2(4),
	SKU_NBR INT, 
	CRT_PGM_ID VARCHAR2(18),
	CRT_TS TIMESTAMP
);

INSERT INTO STG_TLD_ALLOC (TLD_DC_NBR, SKU_NBR, CRT_PGM_ID, CRT_TS)
VALUES ('5097', 1000358177, '123456', CURRENT_TIMESTAMP)